### ISSUE TITLE
Faire défiler le cadre des phases

### ISSUE THREAD

**Issue by Vayel** [Vayel/devin#4]
Quand il y a beaucoup de phases et qu'on scroll pour cliquer sur celles en bas, on ne voit plus le cadre à droite affichant les informations. L'idée serait alors de faire défiler ce cadre avec la page : tant qu'il est entièrement visible, on ne fait rien, mais dès qu'il commence à être chevauché par la barre de navigation, on le descend, sans pour autant aller plus bas que la dernière phase.

**Comment by XAMEUS** [comment]
Peut-être afficher globalement l'information plutôt sous forme de tableau. Avec du détail si on clique sur une phase / fonctionnalité.

Phase / fonctionnalité | Prix
------------ | -------------
Analyse | 340 €
Conception de l'interface | 340 €
Déplacements dans la mission | 340 €
Création d'une mesure | 340 €
Suivi d'étude | 340 €

Après avoir cliqué sur une phase, par exemple "Conception de l'interface", la ligne pourrait s'agrandir pour faire apparaître le détail (objectifs, fonctionnalités, priorités, dépendances, etc.).

**Comment by Vayel** [comment]
@XAMEUS le problème c'est qu'avec ça on affiche directement le prix et le client va se focaliser dessus. Si on lui présente d'abord les choses correctement (objectifs, fonctionnalités détaillées, etc.), ça passera probablement mieux. Mais après peut-être qu'il est préférable en effet d'afficher les informations verticalement, les phases les unes en-dessous des autres. J'ai juste peur que s'il y a beaucoup de phases et qu'elles sont toutes dépliées, il sera plus difficile d'en retrouver une en particulier.

**Comment by Vayel** [comment]
@XAMEUS J'ai essayé une autre config sur la branche `design_vert_steps`. Si #5 se fait, on n'aura probablement plus besoin de la partie "Fonctionnalités" (au pire, on pourra les listes dans les objectifs) et il sera peut-être judicieux de mettre deux phases par ligne pour éviter les devis à rallonge.
